### ISSUE TITLE
✊ Huge thanks!

### ISSUE THREAD

**Issue by babur001** [ako-v/cra-tailwindcss-jit-craco#1]
I have spent a day to configure "jit" in my ubuntu, postcss doesnt seem to work with `npm run watch:css`, and I will  be able to solve it just by `"start": "TAILWIND_MODE=watch craco start",` looking up to your codebase. 
Thanks man!

**Comment by babur001** [comment]
Can you explain a little about why `TAILWIND_MODE=watch craco start` works, however `craco start TAILWIND_MODE=watch` does not?

**Comment by ako-v** [comment]
Your welcome :smiley:
it is because of run order of the commands, first craco watches for changes and serves the built app and then tailwind does it's work that should not have effect on the started app.
