### ISSUE TITLE
TAILWIND_MODE=watch is not recognized as an internal or external command,

### ISSUE THREAD

**Issue by MeAkib** [ako-v/cra-tailwindcss-jit-craco#2]
Hi 

I've cloned your repo and run it after adding packages and got this error.

**_TAILWIND_MODE=watch is not recognized as an internal or external command,_**

Is there any way to ignore it with server.js? I want to use it with just React and Typescript.

Thanks

**Comment by ako-v** [comment]
I think you are using windows, I recommend to use Gitbash in windows, it may solve your problem.
that server file is only for deploy time, you don't need it for development and can safely delete it.

**Comment by lyjk-underdog** [comment]
I got an error when I executed npm start：TAILWIND_MODE=watch is not recognized as an internal or external command

**Comment by ako-v** [comment]
Unfortunately I can not reproduce the problem. can you express more about your problem and the environment you run the template? do you install the dependencies first?

**Comment by AnandBIT** [comment]
If you are on Windows, then your setup is correct but you just need to install `cross-env`,

If you are using npm, intall it as a development dependency by `npm i cross-env -D`, or `npm i cross-env --save-dev`
If you are using yarn, install it as a development dependency by `yarn add cross-env -D`

After installing the package, change your start script like so:

`"start": "cross-env TAILWIND_MODE=watch craco start"`
